services:
  postgres:
    image: postgres:18
    restart: always
    container_name: demo_expo_app
    ports:
      - 5432:5432
    environment:
      POSTGRES_NAME: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
volumes:
  pgdata:
